/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

//import views.biendoinhaukhau.DangKyTamVang;
import views.biendoinhaukhau.DangKyTamTru;
import views.biendoinhaukhau.DangKyTamVang_TraCuu;
import views.biendoinhaukhau.KhaiTu;
import views.biendoinhaukhau.ThayDoiNhanKhau;
import views.biendoinhaukhau.ThemNhanKhau;

/**
 *
 * @author THUAN.HQ183840
 */
public class ChucNang extends javax.swing.JFrame {

    /**
     * Creates new form ChucNang
     */
    public ChucNang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnThemNhanKhau = new javax.swing.JButton();
        btnThayDoiNhanKhau = new javax.swing.JButton();
        btnDangKyTamTru = new javax.swing.JButton();
        btnTamVang = new javax.swing.JButton();
        btnKhaiTu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnThemNhanKhau.setText("Thêm nhân khẩu");
        btnThemNhanKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemNhanKhauActionPerformed(evt);
            }
        });

        btnThayDoiNhanKhau.setText("Thay đổi nhân khẩu");
        btnThayDoiNhanKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThayDoiNhanKhauActionPerformed(evt);
            }
        });

        btnDangKyTamTru.setText("Đăng ký tạm trú");
        btnDangKyTamTru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangKyTamTruActionPerformed(evt);
            }
        });

        btnTamVang.setText("Đăng ký tạm vắng");
        btnTamVang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTamVangActionPerformed(evt);
            }
        });

        btnKhaiTu.setText("Khai Tử");
        btnKhaiTu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhaiTuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnKhaiTu)
                    .addComponent(btnTamVang)
                    .addComponent(btnDangKyTamTru)
                    .addComponent(btnThayDoiNhanKhau)
                    .addComponent(btnThemNhanKhau))
                .addContainerGap(390, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(btnThemNhanKhau)
                .addGap(41, 41, 41)
                .addComponent(btnThayDoiNhanKhau)
                .addGap(42, 42, 42)
                .addComponent(btnDangKyTamTru)
                .addGap(31, 31, 31)
                .addComponent(btnTamVang)
                .addGap(18, 18, 18)
                .addComponent(btnKhaiTu)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemNhanKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemNhanKhauActionPerformed
       dispose();
       ThemNhanKhau them = new ThemNhanKhau();
       them.setLocationRelativeTo(null);
       them.setResizable(false);
       them.setVisible(true);
    }//GEN-LAST:event_btnThemNhanKhauActionPerformed

    private void btnThayDoiNhanKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThayDoiNhanKhauActionPerformed
        ThayDoiNhanKhau thaydoi = new ThayDoiNhanKhau();
        dispose();
        thaydoi.setLocationRelativeTo(null);
        thaydoi.setResizable(false);
        thaydoi.setVisible(true);
    }//GEN-LAST:event_btnThayDoiNhanKhauActionPerformed

    private void btnDangKyTamTruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangKyTamTruActionPerformed
        DangKyTamTru tamTru = new DangKyTamTru();
        dispose();
        tamTru.setLocationRelativeTo(null);
        tamTru.setResizable(false);
        tamTru.setVisible(true);
    }//GEN-LAST:event_btnDangKyTamTruActionPerformed

    private void btnTamVangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTamVangActionPerformed
        DangKyTamVang_TraCuu tamVang = new DangKyTamVang_TraCuu();
        dispose();
        tamVang.setLocationRelativeTo(null);
        tamVang.setResizable(false);
        tamVang.setVisible(true);
    }//GEN-LAST:event_btnTamVangActionPerformed

    private void btnKhaiTuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhaiTuActionPerformed
        KhaiTu khaiTu = new KhaiTu();
        dispose();
        khaiTu.setLocationRelativeTo(null);
        khaiTu.setResizable(false);
        khaiTu.setVisible(true);
    }//GEN-LAST:event_btnKhaiTuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChucNang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChucNang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChucNang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChucNang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChucNang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangKyTamTru;
    private javax.swing.JButton btnKhaiTu;
    private javax.swing.JButton btnTamVang;
    private javax.swing.JButton btnThayDoiNhanKhau;
    private javax.swing.JButton btnThemNhanKhau;
    // End of variables declaration//GEN-END:variables
}
